### ISSUE TITLE
pretrained weights

### ISSUE THREAD

**Issue by kaishijeng** [Hexmagic/LaneDetection#1]
Can you share your pretrained weight? I am interested with deeplab v3 based only

Thanks,

**Comment by Hexmagic** [comment]
> Can you share your pretrained weight? I am interested with deeplab v3 based only
> 
> Thanks,

due to time and resource limit,I can only provide the first stage trained model,See Readme

**Comment by kaishijeng** [comment]
Thanks, I tried it and it works.
When I train with the following script of 50 epochs and run inference with the trained weights, the result is all black (no lane marking has been detected). 

python train.py --batch_size 4 --wid 846 --epochs 50 --lr 0.0006 --back deeplab 

With the same test image, your best.pt is able to detect a lot of lane marking pixels.
Not sure why this happens

Thanks,

**Comment by Hexmagic** [comment]
Maybe my  LR schedule has some problem and cause gradient vanishing,I have updated README,before training you should split data. and you can use visdom to visualize the training progress，10 epochs is enough for the first stage。

**Comment by kaishijeng** [comment]
Get an issue when running python split.py. I only have road2 color images and labels

ThreadPoolExecutor-0_0:  82%|███████████████████████████████████████████████████████████████████████████▉                 | 3380/4140 [16:35<03:40,  3.45it/slibpng error: Read Error  81%|███████████████████████████████████████████████████████████████████████████▋                 | 3368/4140 [16:35<03:48,  3.38it/s]
ThreadPoolExecutor-0_4: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 4140/4140 [20:13<00:00,  3.41it/s]
ThreadPoolExecutor-0_3: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 4140/4140 [20:14<00:00,  3.41it/s]
ThreadPoolExecutor-0_2: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 4140/4140 [20:16<00:00,  3.40it/s]
ThreadPoolExecutor-0_0: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 4140/4140 [20:17<00:00,  3.40it/s]
ThreadPoolExecutor-0_6: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 4140/4140 [20:17<00:00,  3.40it/s]
ThreadPoolExecutor-0_5: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 4140/4140 [20:18<00:00,  3.40it/s]
ThreadPoolExecutor-0_1: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 4140/4140 [20:19<00:00,  3.40it/s]
ThreadPoolExecutor-0_7: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 4139/4139 [20:20<00:00,  3.39it/s]
Traceback (most recent call last):███████████████████████████████████████████████████████████████████████████████████████▊| 4131/4140 [20:17<00:01,  6.05it/s]
  File "./split.py", line 58, in <module>█████████████████████████████████████████████████████████████████████████████████| 4140/4140 [20:18<00:00,  9.61it/s]
    main()Executor-0_6: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 4140/4140 [20:17<00:00,  6.45it/s]
  File "./split.py", line 49, in main████████████████████████████████████████████████████████████████████████████████████▎| 4107/4139 [20:17<00:05,  6.11it/s]
    train_img_, val_img_ = train_test_split(four_paths)██████████████████████████████████████████████████████████████████▍| 4115/4139 [20:18<00:02,  9.03it/s]
  File "/home/test/anaconda3/envs/test/lib/python3.7/site-packages/sklearn/model_selection/_split.py", line 2122, in train_test_split00:01, 11.43it/s]
    default_test_size=0.25)%|█████████████████████████████████████████████████████████████████████████████████████████████| 4139/4139 [20:20<00:00, 14.25it/s]
  File "/home/test/anaconda3/envs/test/lib/python3.7/site-packages/sklearn/model_selection/_split.py", line 1805, in _validate_shuffle_split
    train_size)
ValueError: With n_samples=0, test_size=0.25 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

**Comment by Hexmagic** [comment]
> Get an issue when running python split.py. I only have road2 color images and labels
> 
> ThreadPoolExecutor-0_0: 82%|███████████████████████████████████████████████████████████████████████████▉ | 3380/4140 [16:35<03:40, 3.45it/slibpng error: Read Error 81%|███████████████████████████████████████████████████████████████████████████▋ | 3368/4140 [16:35<03:48, 3.38it/s]
> ThreadPoolExecutor-0_4: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 4140/4140 [20:13<00:00, 3.41it/s]
> ThreadPoolExecutor-0_3: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 4140/4140 [20:14<00:00, 3.41it/s]
> ThreadPoolExecutor-0_2: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 4140/4140 [20:16<00:00, 3.40it/s]
> ThreadPoolExecutor-0_0: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 4140/4140 [20:17<00:00, 3.40it/s]
> ThreadPoolExecutor-0_6: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 4140/4140 [20:17<00:00, 3.40it/s]
> ThreadPoolExecutor-0_5: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 4140/4140 [20:18<00:00, 3.40it/s]
> ThreadPoolExecutor-0_1: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 4140/4140 [20:19<00:00, 3.40it/s]
> ThreadPoolExecutor-0_7: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 4139/4139 [20:20<00:00, 3.39it/s]
> Traceback (most recent call last):███████████████████████████████████████████████████████████████████████████████████████▊| 4131/4140 [20:17<00:01, 6.05it/s]
> File "./split.py", line 58, in █████████████████████████████████████████████████████████████████████████████████| 4140/4140 [20:18<00:00, 9.61it/s]
> main()Executor-0_6: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 4140/4140 [20:17<00:00, 6.45it/s]
> File "./split.py", line 49, in main████████████████████████████████████████████████████████████████████████████████████▎| 4107/4139 [20:17<00:05, 6.11it/s]
> train_img_, val_img_ = train_test_split(four_paths)██████████████████████████████████████████████████████████████████▍| 4115/4139 [20:18<00:02, 9.03it/s]
> File "/home/test/anaconda3/envs/test/lib/python3.7/site-packages/sklearn/model_selection/_split.py", line 2122, in train_test_split00:01, 11.43it/s]
> default_test_size=0.25)%|█████████████████████████████████████████████████████████████████████████████████████████████| 4139/4139 [20:20<00:00, 14.25it/s]
> File "/home/test/anaconda3/envs/test/lib/python3.7/site-packages/sklearn/model_selection/_split.py", line 1805, in _validate_shuffle_split
> train_size)
> ValueError: With n_samples=0, test_size=0.25 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

I have updated  script.py ,check your data location is right,and run
 `python split.py --root data --roads 2`

**Comment by kaishijeng** [comment]
Where do you download  Gray_Label_New.zip?
I don't see it at this website:
http://apolloscape.auto/lane_segmentation.html

Are your ColorImage_road02.zip,ColorImage_road04.zip the same as ColorImage_road02.tar,gz,ColorImage_road04.tar.gz on Baidu website above?

Thanks,

**Comment by Hexmagic** [comment]
> Where do you download Gray_Label_New.zip?
> I don't see it at this website:
> http://apolloscape.auto/lane_segmentation.html
> 
> Are your ColorImage_road02.zip,ColorImage_road04.zip the same as ColorImage_road02.tar,gz,ColorImage_road04.tar.gz on Baidu website above?
> 
> Than

here,https://aistudio.baidu.com/aistudio/datasetDetail/3624

**Comment by kaishijeng** [comment]
I am able to download Gray_Label_New.zip and everything works now.
What are scripts for stage 2 and 3 training?
Thanks,

**Comment by Hexmagic** [comment]
change param `wid`  and use pretrained weight
```
python train.py --wid 1692 --weigths weights/best.pt
python train.py --wid 3384 --weigths weights/best.pt
```

**Comment by Hexmagic** [comment]
> I am able to download Gray_Label_New.zip and everything works now.
> What are scripts for stage 2 and 3 training?
> Thanks,

**Comment by Hexmagic** [comment]
> I am able to download Gray_Label_New.zip and everything works now.
> What are scripts for stage 2 and 3 training?
> Thanks,

change param wid and use pretrained weight

python train.py --wid 1692 --weigths weights/best.pt
python train.py --wid 3384 --weigths weights/best.pt
