### ISSUE TITLE
MIOU达到0.8多，正确么

### ISSUE THREAD

**Issue by zy199676** [Hexmagic/LaneDetection#3]
您好，运行您的代码后第一阶段miou就达到了0.8多，我看到其余百度数据集有关项目中miou只有0.6多，请问这是什么原因呢

**Comment by Hexmagic** [comment]
正确的，后面扩大采样面积会降低的。

**Comment by zy199676** [comment]
我看到有些项目里写的是0.6多，咱们这个会达到多少呢？我看的是19年比赛的第一名写的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Hexmagic/LaneDetection"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月20日(星期三) 中午11:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Hexmagic/LaneDetection] MIOU达到0.8多，正确么 (Issue #3)





 
正确的，后面扩大采样面积会降低的。

**Comment by Hexmagic** [comment]
这个是后面写的，老师带的项目。大概0.75多，有条件应该能到0.8。

**Comment by zy199676** [comment]
> 这个是后面写的，老师带的项目。大概0.75多，有条件应该能到0.8。

感谢您的耐心回复，我最近在看有关Unet，deeplab的百度数据集的一些实验，我的困惑是，您的MIOU指标和其余的项目比较达到了很好的效果。我还没有仔细阅读您的代码，您能告知下您MIOU指标提升很大的创新点主要在哪么。是主要在数据集的划分么。
另外我在运行其余有关项目时，miou只有0.3，您知道这些项目的主要区别在哪么，才能有比较大的区别。谢谢

**Comment by Hexmagic** [comment]
这个是他们比赛完跑的，后面数据有更新肯定比比赛的时候好一点。主要就是调参和修改一些层数据增强，分段减少学习率之类的常规常规方法。这个你miou小可能是你计算方法有问题或者模型不对。最好用一些现成模型的测试下baseline 。分割可以参考这个https://github.com/qubvel/segmentation_models.pytorch.git。模型正确率主要还是调参数和数据增强 你可以用一些比较新的技术试试

**Comment by zy199676** [comment]
非常感谢，
